"""Optional install extras derived from bundled skill manifests."""

from __future__ import annotations

from pathlib import Path
from typing import Dict, Iterable, List, Mapping, Optional, Sequence, Tuple

import yaml

from skillware.core.discovery import bundled_skills_root, list_registry_skill_ids

# Packages in [project.dependencies] — manifest entries matching these are omitted
# from category, skill, and [all] extras.
CORE_DEPENDENCIES: frozenset[str] = frozenset(
    {
        "requests",
        "pyyaml",
        "python-dotenv",
        "beautifulsoup4",
        "packaging",
        "jsonschema",
        "rich",
    }
)

# Manifest distribution names that resolve to a core dependency.
_REQUIREMENT_CORE_ALIASES: Mapping[str, str] = {
    "bs4": "beautifulsoup4",
}

GENERATED_BEGIN = "# --- extras: begin generated by scripts/sync_extras.py ---"
GENERATED_END = "# --- extras: end generated by scripts/sync_extras.py ---"


def bundled_skills_dir(skills_root: Optional[Path] = None) -> Path:
    return skills_root if skills_root is not None else bundled_skills_root()


def normalize_pkg_name(requirement: str) -> str:
    """Return the normalized PyPI distribution name for a requirement string."""
    pkg = requirement.split(";")[0].strip()
    for sep in ("==", ">=", "<=", "!=", "~=", ">", "<"):
        if sep in pkg:
            pkg = pkg.split(sep, 1)[0].strip()
            break
    pkg = pkg.lower()
    return _REQUIREMENT_CORE_ALIASES.get(pkg, pkg)


def is_core_requirement(requirement: str) -> bool:
    return normalize_pkg_name(requirement) in CORE_DEPENDENCIES


def filter_non_core(requirements: Optional[Sequence[str]]) -> List[str]:
    """Keep manifest requirements that are not satisfied by core dependencies."""
    seen: set[str] = set()
    filtered: List[str] = []
    for req in requirements or []:
        if not str(req).strip():
            continue
        req = str(req).strip()
        key = normalize_pkg_name(req)
        if is_core_requirement(req) or key in seen:
            continue
        seen.add(key)
        filtered.append(req)
    return filtered


def registry_id_to_extra(registry_id: str) -> str:
    category, skill = registry_id.split("/", 1)
    return f"{category}_{skill}"


def extra_to_registry_id(
    extra: str,
    categories: Optional[Iterable[str]] = None,
) -> Optional[str]:
    if extra in {"all", "dev", "gemini", "claude", "openai", "agents"}:
        return None
    if categories is None:
        return None
    for category in sorted(set(categories), key=len, reverse=True):
        prefix = f"{category}_"
        if extra.startswith(prefix):
            skill = extra[len(prefix) :]
            if skill:
                return f"{category}/{skill}"
    return None


def _load_manifest(skill_dir: Path) -> dict:
    manifest_path = skill_dir / "manifest.yaml"
    if not manifest_path.is_file():
        return {}
    data = yaml.safe_load(manifest_path.read_text(encoding="utf-8"))
    return data if isinstance(data, dict) else {}


def collect_skill_requirements(
    skills_root: Optional[Path] = None,
) -> Dict[str, List[str]]:
    """Map registry skill id -> non-core manifest requirements."""
    root = bundled_skills_dir(skills_root)
    result: Dict[str, List[str]] = {}
    for skill_id in list_registry_skill_ids(root):
        manifest = _load_manifest(root / skill_id)
        result[skill_id] = filter_non_core(manifest.get("requirements"))
    return result


def collect_category_requirements(
    skill_requirements: Mapping[str, Sequence[str]],
) -> Dict[str, List[str]]:
    """Union non-core requirements for each category."""
    by_category: Dict[str, List[str]] = {}
    for skill_id, reqs in skill_requirements.items():
        category = skill_id.split("/", 1)[0]
        existing = by_category.setdefault(category, [])
        for req in reqs:
            key = normalize_pkg_name(req)
            if any(normalize_pkg_name(item) == key for item in existing):
                continue
            existing.append(req)
    for category in by_category:
        by_category[category].sort(key=normalize_pkg_name)
    return dict(sorted(by_category.items()))


def collect_all_requirements(
    skill_requirements: Mapping[str, Sequence[str]],
) -> List[str]:
    """Deduped union of all non-core skill requirements."""
    merged: List[str] = []
    for reqs in skill_requirements.values():
        for req in reqs:
            key = normalize_pkg_name(req)
            if any(normalize_pkg_name(item) == key for item in merged):
                continue
            merged.append(req)
    merged.sort(key=normalize_pkg_name)
    return merged


def build_extras_map(skills_root: Optional[Path] = None) -> Dict[str, List[str]]:
    """Return generated optional-dependency groups (categories, skills, all)."""
    skill_reqs = collect_skill_requirements(skills_root)
    extras: Dict[str, List[str]] = {}

    for category, reqs in collect_category_requirements(skill_reqs).items():
        extras[category] = list(reqs)

    for skill_id in sorted(skill_reqs):
        extras[registry_id_to_extra(skill_id)] = list(skill_reqs[skill_id])

    extras["all"] = collect_all_requirements(skill_reqs)
    return extras


def format_requirements_list(requirements: Sequence[str]) -> str:
    if not requirements:
        return "[]"
    lines = ["["]
    for req in requirements:
        lines.append(f'    "{req}",')
    lines.append("]")
    return "\n".join(lines)


def render_generated_block(skills_root: Optional[Path] = None) -> str:
    skill_reqs = collect_skill_requirements(skills_root)
    category_reqs = collect_category_requirements(skill_reqs)
    lines = [GENERATED_BEGIN, ""]

    for name in sorted(category_reqs):
        lines.append(f"{name} = {format_requirements_list(category_reqs[name])}")
        lines.append("")

    for skill_id in sorted(skill_reqs):
        name = registry_id_to_extra(skill_id)
        lines.append(f"{name} = {format_requirements_list(skill_reqs[skill_id])}")
        lines.append("")

    lines.append(
        f"all = {format_requirements_list(collect_all_requirements(skill_reqs))}"
    )
    lines.append("")
    lines.append(GENERATED_END)
    return "\n".join(lines)


def build_missing_requirements_message(
    manifest: Mapping[str, object],
    registry_id: Optional[str],
    missing: Sequence[str],
) -> str:
    """Build a pip install hint when manifest requirements are not importable."""
    skill_name = str(manifest.get("name") or registry_id or "unknown")
    missing_list = ", ".join(missing)
    lines = [
        f"Skill '{skill_name}' requires missing packages: {missing_list}.",
        "",
    ]

    if registry_id:
        skill_extra = registry_id_to_extra(registry_id)
        category = registry_id.split("/", 1)[0]
        lines.extend(
            [
                "Install the skill runtime extra:",
                f'  pip install "skillware[{skill_extra}]"',
                "",
                "Or install all skills in the category:",
                f'  pip install "skillware[{category}]"',
                "",
                "Or install runtime deps for every bundled skill:",
                '  pip install "skillware[all]"',
            ]
        )
    else:
        lines.append(f"Please run: pip install {' '.join(missing)}")

    return "\n".join(lines)


def extras_for_registry_id(registry_id: str) -> Tuple[str, str]:
    """Return (category_extra, skill_extra) names for a registry skill id."""
    category = registry_id.split("/", 1)[0]
    return category, registry_id_to_extra(registry_id)
